language: shell
services:
  - docker

env:
  global:
    # DOCKER_USERNAME
    - secure: "tFq/iOSqKVvpEN3KsjPS+1yEQnmp9EWNYcRGMRIX8ub869srMi0ww5ms7mc1i9vOE/W8r0T9x55Gj1Yjc7Zn5VyMPMyjpPJ2mq926hrmgAi0KnpsCSZiGdMaRK4xXpIL9A/F+MtvGHlUa9NMgKwsVIZnss86vHGMMa1CCeMXQmiosv3Cuh7VNJIerv6PC4X3SREK3c9k2hTHeGpnBpzEeA0iO4BGqFsJC4otiFomO/DFiR+aoYJSQw+S6t3XRWWY+UpYO73xG5Pguy82tcxcIBFJ04wjwuG6UycBLNODefFOqNn9frjKTHqQHuBiS2jtdr3gxYI9ZIgPayuVXYHcOiM9PGf9zxcR6Iom1YcaKn0fl3WVReLp0rUEerxkdHsXCbW/InXwfjT+xA3mvF/BCG7XzlrSC0S9TzWiHG6uosp2oN7o8/vtKmj6r2GNyaY3Kew7/QIvKPuYn1q41KpDS87kfM4tWqp6O8AIFT0Efo9VB/7ry1Oa8+Xh2YnrXNXn97nEVdAdwaUeLfXhdRyiHVyK7CxNk+rEcCmSRF9UGgxHpGBPhvNA0FzjV7jlEYIOqGZK9QJHyH/K8BHZDi+9ZYqje2CSri7fpEplG5TklXtFR98WzucG6hHcDJMjCSms2AQYBEBB93I1q0fbldmsh7pKACf2wbrHSOpyHB65EFQ="
    # DOCKER_ACCESS_TOKEN
    - secure: "n0jVb/ji89K56uZmgz79xKPAbi3jtx1QaGtrpuEpNMH4DHnMQKTNcBW57nyKQGcLOJapOtvMGT4UgxH0SH6lnPhmo6NGnA2Dz8MbeVDJp8VtrODIwgqdB9eV2WJEosriKh2Wlg4ckzRYgM7gGuhyRRLHKtWWLjW23wi1R8bPruV07HAb1EIKUzMU3yeYuQn4MO5HtDhO2zyvQmfFOI8emPqrBVLXmgNzosW1/n6NCxmody4uihnsmvTlZpZmglOt0mmD+Kr19Nfd+YiKXJWwagOm7vxopPbi991XSPj0QBKL5Ss4HD2Op7Ol96dImKr+gmf6PlobjSBB8BvDSlYxLeco4ewvGo8QXylf2PJ1Iu6DxOXmlyZ8Nm3WsPDoTr9zqPyRfQ9UR4YYEzIMpBXR5ICip/grarae8NEE+sItYu5WNUZv2tnaxPZx4loD4EAUnJ4EIC/SdZwdds9yn0IaRGyIM8B4PP3raWzdxVXk5BeaqaLxqhgzmTNd/Lyg1mBw7iYOKfjX6s9hWE581QfwW2a0wmkpcVDNXmPcQdI2+Vof3anzjTYKUCtsKaSqK/KKG/nGdHXNIa4rUNI4+SBYjx4u+8SpPriMjw+x2omSeDTn96DGglN7OTfjvkzD13uAleM6v5oSQ12QvGZkvPWBx46XFawy5kkyfi4WoOiNNSA="
    - IMAGE_NAME=baloiseincubator/stock-service

install: skip

script:
  - docker build -t $IMAGE_NAME:$TRAVIS_COMMIT .
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" != "master" ]; then docker push $IMAGE_NAME:$TRAVIS_COMMIT; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:latest; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then docker push $IMAGE_NAME:latest; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then docker push $IMAGE_NAME:$TRAVIS_COMMIT; fi
  - if [ -n "$TRAVIS_TAG" ]; then docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:$TRAVIS_TAG; fi
  - if [ -n "$TRAVIS_TAG" ]; then docker push $IMAGE_NAME:$TRAVIS_TAG; fi