language: shell
services:
  - docker

env:
  global:
    # DOCKER_USERNAME
    - secure: "tFq/iOSqKVvpEN3KsjPS+1yEQnmp9EWNYcRGMRIX8ub869srMi0ww5ms7mc1i9vOE/W8r0T9x55Gj1Yjc7Zn5VyMPMyjpPJ2mq926hrmgAi0KnpsCSZiGdMaRK4xXpIL9A/F+MtvGHlUa9NMgKwsVIZnss86vHGMMa1CCeMXQmiosv3Cuh7VNJIerv6PC4X3SREK3c9k2hTHeGpnBpzEeA0iO4BGqFsJC4otiFomO/DFiR+aoYJSQw+S6t3XRWWY+UpYO73xG5Pguy82tcxcIBFJ04wjwuG6UycBLNODefFOqNn9frjKTHqQHuBiS2jtdr3gxYI9ZIgPayuVXYHcOiM9PGf9zxcR6Iom1YcaKn0fl3WVReLp0rUEerxkdHsXCbW/InXwfjT+xA3mvF/BCG7XzlrSC0S9TzWiHG6uosp2oN7o8/vtKmj6r2GNyaY3Kew7/QIvKPuYn1q41KpDS87kfM4tWqp6O8AIFT0Efo9VB/7ry1Oa8+Xh2YnrXNXn97nEVdAdwaUeLfXhdRyiHVyK7CxNk+rEcCmSRF9UGgxHpGBPhvNA0FzjV7jlEYIOqGZK9QJHyH/K8BHZDi+9ZYqje2CSri7fpEplG5TklXtFR98WzucG6hHcDJMjCSms2AQYBEBB93I1q0fbldmsh7pKACf2wbrHSOpyHB65EFQ="
    # DOCKER_ACCESS_TOKEN
    - secure: "fND4CtHM5Z4cMqvAAvbrsLg3S3j6lI/6ksVWsKaPLC9zNjdl1M5BQNkOQPkHlKHZLl1QbNVJMN7N6r0qS84PvtXLjnhlHf9kG/6NN2spUL0SR4KmlYGJNKgAokmo3gOXx1gXmD5uQ0qF+J81zuHQ0Z3eZtZfKqa/qAhnNUZBv3Gy5CXzKKtegvT0Z6jBtc+Bwz6vnR73p7OSjLENIKf8XYNG/ZrtoYxQSyelKhHIeV3XFLnaiCJ2SLZScgab1d+WbrSvRba6c/IOHjNJCAwTGV+KeWRHu3S1LOC4aud+pWofEaPEXue8FqOcmU9s97HDWleB9ubqvxR0Lz7lSQhzZKc9X82vWpHhfWGzLaAdCzt1HcG8oDldY/pQERjgqEmeUgqd6LFATWxRrQBBD82rb0QCtgQT0yX0gOxR7qBrgyvX1G+V5dB0NDNmHQvVE8Zaq0bVr9BIGYSK1QhIUvd5hfC6RMLM5YufqScsiF2L2BGuXyOU/EpA9eAQp+g2pnkCtZDsMgpeMze1dm79RM9ec+LIraGjQ5oBMLUBi1v1sE7OUahHrnz9jqXoiLVwBrn89SOhmBl6K2Z+Z/GRBQOrXwh6JCqIgtNuQF+ohLDfpwtkUgtNSzrxWKFxdiu3JoljrKccU+MhxqTyTZRUVW7DUGuvcgAgFOYyeyg3BwfjIKs="
    - IMAGE_NAME=baloiseincubator/stock-service

install: skip

script:
  - docker build -t $IMAGE_NAME:$TRAVIS_COMMIT .
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" != "master" ]; then docker push $IMAGE_NAME:$TRAVIS_COMMIT; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:latest; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then docker push $IMAGE_NAME:latest; fi
  - if [ -n "$TRAVIS_TAG" ]; then docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:$TRAVIS_TAG; fi
  - if [ -n "$TRAVIS_TAG" ]; then docker push $IMAGE_NAME:$TRAVIS_TAG; fi